name: Ogma Gradle Build

on: [ pull_request ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build bootJar
        run: cd bot && ./gradlew bootJar